### ISSUE TITLE
In left-handed mode ($100 ETH or BTC BOUNTY)

### ISSUE THREAD

**Issue by alucardzlh** [RogueMaster/flipperzero-firmware-wPlugins#1002]
### Describe the bug.

Hello, I found that when the firmware is switched to left-hand mode, the left and right buttons will be reversed in the wrong direction. Version number: RM1130-1445-0.93.9-d9db571

### Reproduction

1. On the home page 
2. Press up to enter the quick panel 
3. Click the left-hand mode button in the upper left corner

### Target

RM1130-1445-0.93.9-d9db571

### Anything else?

($100 USD in ETH or BTC bounty for working app...) PR Submission and DM on Discord with wallet address.

If you are a Patreon supporter and would value this functionality, please DM on Patreon and I will add your monthly subscription to the prize allotment. If you have specific stipulations on how you want it to behave, feel free to detail them in a comment here for review.

**Comment by BKBobbyDigital** [comment]
Noting this is still an issue (buttons inversed when in lefty mode) in 0.93.9 18-01-2024.

**Comment by Techno3600** [comment]
Just wanted to chime in and say this is still an issue. I really liked lefty mode on the default firmware, and I'd really like to be able to use it with RogueMaster!

**Comment by RogueMaster** [comment]
Please do submit a PR if you can find a solution.  We don't need any useless chimes unless it's a solution. I've spent enough time investigating this minor issue.

**Comment by Techno3600** [comment]
> Please do submit a PR if you can find a solution. We don't need any useless chimes unless it's a solution. I've spent enough time investigating this minor issue.

Hi! I don't code in this language, so I can't submit a PR. That would be the job of the people who maintain the project/applicable contributors.

This is not a minor issue. As a lefty, I found lefty mode on the default software to be extremely helpful in using the Flipper, and having to switch back to righty mode just to access the features of this software is frustrating. Your software/plugins are great (and I love using it) but it requires converting back to righty mode, which could be easily fixed by just inverting the arrow keys in the software.

**Comment by aryn832** [comment]
https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/1063

**Comment by RogueMaster** [comment]
Confirm with me on Discord your ETH address and it shall be sent.
