### ISSUE TITLE
Furi Check Failed

### ISSUE THREAD

**Issue by SneezyLlama** [RogueMaster/flipperzero-firmware-wPlugins#1104]
### Describe the bug.

Whenever the flipper is powered off and then on again, it crashes and reboots with a message saying "furi_check failed".

### Reproduction

Switch on the flipper.

**Comment by benleb** [comment]
This issue still exists (or came back) with the current 420 branch

**Comment by RogueMaster** [comment]
Delete your dolphin and app folders and re-install the firmware 😄

**Comment by benleb** [comment]
okay, thanks 😄👍

**Comment by ATr0jan** [comment]
I Reflashed with DFU back to stock and reformatted the SD Card before reloading the Latest RM firmware and i am still seeing this Error

**Comment by A2-Dev** [comment]
FWIW i tried installing RM multiple ways (copying files to SD, coping to update folder, qflipper) and kept getting this error even after i deleted apps and dolphin dirs and reinstalled. Would only crash on boot up if SD card was inserted. if you start it up without SD card inserted and then insert SD card it would work fine. Crash once then it worked fine if you started with SD card installed.

Tried today with a smaller SD card 32gb Samsung Evo instead of the original 64gb Samsung Evo). Not sure if someone else could try and reproduce. Just curious if it's the SD card as I've seen it cause RPi issues in the past.

**Comment by RogueMaster** [comment]
It's very likely an SD thing since others have had the error subside after swapping SD

**Comment by huuck** [comment]
It's not an SD thing, it's still happening even after testing 3 different SD cards.
