### ISSUE TITLE
Calculator bug

### ISSUE THREAD

**Issue by Foul** [RogueMaster/flipperzero-firmware-wPlugins#296]
### Describe the bug.

The calculator is bugged using % operation.. always give 0

### Reproduction

Launch Calculator
Try :
100+1%
=
0

**Comment by pasolano** [comment]
The [tinyexpr](https://github.com/codeplea/tinyexpr/) library interprets `%` as modulo instead of as a percentage sign, which is different from how [common four-function calculators](https://devblogs.microsoft.com/oldnewthing/20080110-00/?p=23853) interpret that symbol.

Modulo is likely more helpful to the audience of this firmware than having a dedicated percentage function, but if the design philosophy for this tool is to match physical calculators as closely as possible, then it should change.

**Comment by RogueMaster** [comment]
Please ask creator
