### ISSUE TITLE
Frequency analyzer

### ISSUE THREAD

**Issue by sky7d** [RogueMaster/flipperzero-firmware-wPlugins#477]
### Describe the bug.

In the last fw frequency happens that frequency analyzer doesn't work anymore...in the net many devices have this kinf of problems

### Reproduction

Happen suddendly and the frquency analyzer doe sn't mwork anymore

### Target

Frequency analyzer

**Comment by RogueMaster** [comment]
> in the net many devices have this kinf of problems

This is not true. I have tested with another flipper and the Frequency analyzer works perfectly.

**Comment by sky7d** [comment]
I found several people in different forums who had the same problem as me
so i reported the bug. I reinstalled the original fw and the frequency
analyzer came back to life...





                            Merry Xmas Marco

Il giorno dom 25 dic 2022 alle ore 18:41 RogueMaster <
***@***.***> ha scritto:

**Comment by RogueMaster** [comment]
Happy Holidays Marco! Other peoples issues won't necessarily be your own. If those people truly have issues, why aren't they in my Discord instead of some random forum. 

If you are on the latest firmware, the Frequency Analyzer is tested to be working. Both with another flipper and my car key that has a weak signal.
