### ISSUE TITLE
Battery percentage unreadable

### ISSUE THREAD

**Issue by hasmar04** [RogueMaster/flipperzero-firmware-wPlugins#71]
**Describe the bug**
The battery percentage that is overlayed on the battery meter is unreadable due to the font not fitting within the battery meter area, flowing into the white space around it. 

**To Reproduce**
1. Switch on...
2. Check battery meter

**Expected behavior**
The battery meter be readable. 

**Additional context**
I have not checked how it looks when the battery is depleted as I don't let my flipper charge get that low. 
I also noticed there is no way to turn it off for people, who unlike me, don't want a percentage. 
Other option is having percentage in the place of the meter, and make the battery icon not visible?

**Comment by RogueMaster** [comment]
Original developer will work on it more and make the settings work. In the meantime, this is what we have. When it is lower, the text changes to be black instead of white. I could also make the battery empty and show only percentage. Will mess around and figure out if empty works better. However, if  you prefer not to have it, I would advise compiling it to your liking.
