### ISSUE TITLE
Seader app not working (works on original firmware)

### ISSUE THREAD

**Issue by Antiklesys** [RogueMaster/flipperzero-firmware-wPlugins#743]
### Describe the bug.

When reading an iclass SE card using the Seader app in Roguemaster it fails.
Using the original firmware + the seader app installed from the mobile app it works flawlessly.
I spoke with the creator of the Seader app and it seems the error log is throwing errors that were fixed in the latest release.
I suspect the seader app code in roguemaster is stale compared to latest release.

### Reproduction

1- Install roguemaster firmware fresh
2- add the sam+nard reader to the flipper zero
3- scan an iclass SE card with the seader app using the picopass function
4- errors out
5- install original firmware
6- connect to mobile phone via bluetooth and install the seader app from the store
7- perform steps 2 &3 and it will read the card correctly

**Comment by RogueMaster** [comment]
Seader issues would usually be in the Seader repo, however, this issue seems to be more an issue with a past release that is currently already updated in the public RM release.

**Comment by RogueMaster** [comment]
Correction, latest public release has the latest changes for the Seader app

**Comment by RogueMaster** [comment]
Are you on the latest public release @Antiklesys ? Please confirm the build date and hash for your build.

**Comment by Antiklesys** [comment]
@RogueMaster I'm on the latest public release

RM0905-0900-0.90.2-95c6220

build date 2 days ago

**Comment by Antiklesys** [comment]
Build date is 2 days ago.

**Comment by bettse** [comment]
Specifically I saw lines like
`66487 [34m[D][SeaderWorker] [0mTransmit (500 timeout) 4 bytes [0c05de64] via 4 (icla)s`
in ATK's logs, which was fixed in seader f991626b5c18fc6d5803d56617e83659ffecf9d4 (specifically the ` (icla)s` thing).  Curiously, I see the same code change (https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/420/applications/external/seader/seader_worker.c#L754), so I'm not sure why it is present in their logs.  

Overall though, they were having errors (ex "Unknown block...") with seader on RM, but worked fine on the official flipper firmware, which I think is what lead them to post here, as opposed to in the seader repo.
